Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # master VM
  config.vm.define "devhub-masternode01" do |master|
    master.vm.hostname = "devhub-masternode01"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "3096"
      vb.cpus = 2
    end
  end

  # worker VM
  config.vm.define "devhub-workernode01" do |worker|
    worker.vm.hostname = "devhub-workernode01"
    worker.vm.network "private_network", ip: "192.168.56.11"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "3096"
      vb.cpus = 2
    end
  end
end
